version: "3.7"

services:
  mc:
    image: joaolboing/minecraft-server
    container_name: mc
    ports:
      - 25565:25565
    volumes:
      - ./data:/data
      - ./plugins/:/plugins

    environment:
      - VERSION=1.14.4
      - TYPE=SPIGOT
      - SERVER_NAME=Conectra
      - EULA=true
      - MEMORY=3G
      - GUI=false
      - CONSOLE=false
